ajit_2:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  wheel_position_controller:
    type: position_controllers/JointGroupPositionController
    joints: [rear_right_wheel,front_right_wheel,rear_left_wheel,front_left_wheel]
    pid: {p: 1.0, i: 1.0, d: 1.0, i_clamp_min: -10.0, i_clamp_max: 10.0}

  robot_position_controller:
    type: position_controllers/JointGroupPositionController
    joints: [head,left_lower_arm,left_shoulder_joint,left_shoulder,left_upper_arm,left_hand,neck,right_lower_arm,right_shoulder_joint,right_shoulder,right_upper_arm,right_hand]
    pid: {p: 1.0, i: 1.0, d: 1.0, i_clamp_min: 0.0, i_clamp_max: 3.14}
